version: '3.9'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'hr'
      MYSQL_PASSWORD: 'azia2020'
      MYSQL_ROOT_PASSWORD: 'azia2020'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alibou
      - MONGO_INITDB_ROOT_PASSWORD=alibou
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=alibou
      - ME_CONFIG_MONGODB_ADMINPASSWORD=alibou
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongo: {}
