version: '3.9'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'hr'
      MYSQL_PASSWORD: 'azia2020'
      MYSQL_ROOT_PASSWORD: 'azia2020'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - webapp

  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "9381:8080"
    networks:
      - webapp

networks:
  webapp:

volumes:
  my-db: